```sql
USE DATABASE RISKGUARD_DB;
USE SCHEMA RISK;

CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID VARCHAR,
    CUSTOMER_NAME VARCHAR,
    AGE INTEGER,
    CITY VARCHAR,
    COUNTRY VARCHAR,
    OCCUPATION VARCHAR,
    CUSTOMER_RISK_LEVEL VARCHAR,
    KYC_STATUS VARCHAR,
    ACCOUNT_OPEN_DATE DATE
);

CREATE OR REPLACE TABLE ACCOUNTS (
    ACCOUNT_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    ACCOUNT_TYPE VARCHAR,
    BALANCE NUMBER(18,2),
    ACCOUNT_STATUS VARCHAR
);

CREATE OR REPLACE TABLE TRANSACTIONS (
    TRANSACTION_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    TRANSACTION_DATE TIMESTAMP,
    TRANSACTION_TYPE VARCHAR,
    AMOUNT NUMBER(18,2),
    MERCHANT VARCHAR,
    BENEFICIARY_ACCOUNT VARCHAR,
    BENEFICIARY_COUNTRY VARCHAR,
    CHANNEL VARCHAR,
    TRANSACTION_STATUS VARCHAR
);

CREATE OR REPLACE TABLE RISK_SIGNALS (
    SIGNAL_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    SIGNAL_TYPE VARCHAR,
    SEVERITY VARCHAR,
    RISK_SCORE INTEGER,
    DESCRIPTION VARCHAR,
    DETECTED_AT TIMESTAMP
);

CREATE OR REPLACE TABLE INVESTIGATIONS (
    INVESTIGATION_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    SIGNAL_ID VARCHAR,
    STATUS VARCHAR,
    FINDING VARCHAR,
    RECOMMENDED_ACTION VARCHAR,
    CREATED_AT TIMESTAMP
);

CREATE OR REPLACE TABLE REGULATORY_DOCUMENTS (
    DOCUMENT_ID VARCHAR,
    DOCUMENT_TITLE VARCHAR,
    REGULATION_AREA VARCHAR,
    JURISDICTION VARCHAR,
    DOCUMENT_TEXT VARCHAR,
    SOURCE_TYPE VARCHAR
);
```

