CREATE OR REPLACE DATABASE RISKGUARD_DB;

CREATE OR REPLACE SCHEMA RISKGUARD_DB.RISK;

CREATE OR REPLACE WAREHOUSE RISKGUARD_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE RISKGUARD_WH;
USE DATABASE RISKGUARD_DB;
USE SCHEMA RISK;
