```sql
USE DATABASE RISKGUARD_DB;
USE SCHEMA RISK;

-- ============================================
-- RISKGUARD AI DASHBOARD VIEWS
-- ============================================

-- Executive dashboard metrics
CREATE OR REPLACE VIEW DASHBOARD_METRICS AS
SELECT
    COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS,

    COUNT(
        DISTINCT CASE
            WHEN CUSTOMER_RISK_LEVEL = 'HIGH'
            THEN CUSTOMER_ID
        END
    ) AS HIGH_RISK_CUSTOMERS,

    COUNT(
        DISTINCT CASE
            WHEN RISK_SIGNAL_COUNT > 0
            THEN CUSTOMER_ID
        END
    ) AS FLAGGED_CUSTOMERS,

    SUM(TOTAL_TRANSACTION_AMOUNT) AS TOTAL_TRANSACTION_VALUE,

    SUM(HIGH_VALUE_TRANSACTION_AMOUNT) AS HIGH_VALUE_TRANSACTION_VALUE

FROM RISK_SUMMARY;


-- High-risk customer investigation view
CREATE OR REPLACE VIEW HIGH_RISK_CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    OCCUPATION,
    CUSTOMER_RISK_LEVEL,
    KYC_STATUS,
    TOTAL_TRANSACTIONS,
    TOTAL_TRANSACTION_AMOUNT,
    HIGH_VALUE_TRANSACTION_COUNT,
    HIGH_VALUE_TRANSACTION_AMOUNT,
    RISK_SIGNAL_COUNT,
    MAX_RISK_SCORE

FROM RISK_SUMMARY

WHERE CUSTOMER_RISK_LEVEL = 'HIGH'

ORDER BY MAX_RISK_SCORE DESC;
```
